<hr />
<div class="row">
    <div class="col-md-8">
        <h1>Products</h1>
    </div>
    <div class="col-md-2 text-right">
        <?php
        if($this->cartHelper()->allowCartUse() === true) {
            if ($this->cartHelper()->isEmpty() === true) {
                echo "<i>Your Cart is empty.</i>";
            }
        }
        ?>
    </div>
    <div class="col-md-2">
        <?php
            if($this->cartHelper()->allowCartUse() === true) {
                if( isset($forms) && is_array($forms) && array_key_exists('form_cart_access',$forms)) {
                    $form_cart_access = $forms['form_cart_access'];
                    $form_cart_access->prepare();
                    echo $this->form()->openTag($form_cart_access);
                    echo $this->formCollection($form_cart_access);
                    echo $this->form()->closeTag();
                }
            }
        ?>
    </div>
</div>

<hr />

<?php if(isset($messages)&&array_key_exists('error',$messages)):?>
    <?=$this->flashMessage($messages['error'],'error');?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('info',$messages)):?>
    <?=$this->flashMessage($messages['info'],'info');?>
<?php endif;?>

<?php if( ! empty($list)): ?>
    <table class="table table-hover" style="table-layout: fixed;">
        <thead class="thead-light">
        <tr>
            <th COLSPAN="2">Name</th>
            <th>Price</th>
            <?php if($this->cartHelper()->allowCartUse() === true):?>
            <th class="text-right">Add to Cart</th>
            <?php endif;?>
        </tr>
        </thead>
        <tbody>
        <?php
        /* @var \Product\Model\ProductModel $product */
        foreach($list as $product):
            echo $this->partial('product::product-list-table-row', ['product'=>$product,'forms'=>(isset($forms))?$forms:null]);
        endforeach; ?>
        </tbody>
    </table>

<?php endif; ?>

<?php if( isset($form_cart_access) && ! empty($form_cart_access)): ?>
    <?php
    $form_cart_access->prepare();
    echo $this->form()->openTag($form_cart_access);
    echo $this->formCollection($form_cart_access);
    echo $this->form()->closeTag();
    ?>
<?php endif;?>
