<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-5">
            <?php if(isset($messages)&&array_key_exists('error',$messages)):?>
                <?=$this->flashMessage($messages['error'],'error',true,true);?>
            <?php endif;?>
            <?php if(isset($messages)&&array_key_exists('success',$messages)):?>
                <?=$this->flashMessage($messages['success'],'success',true,true);?>
            <?php endif;?>
            <?php if(isset($messages)&&array_key_exists('info',$messages)):?>
                <?=$this->flashMessage($messages['info'],'info',true,true);?>
            <?php endif;?>
        </div>
    </div>
    <div class="row justify-content-md-center">
        <div class="col-5">
            <?php if(is_array($forms) && ! empty($forms) && array_key_exists('form_login',$forms)): ?>
                <?php
                $loginForm = $forms['form_login'];
                $loginForm->prepare();
                ?>

                <?=$this->form()->openTag($loginForm);?>

                <div class="form-group pb-1 pt-3 pl-3 pr-3 mb-0">
                    <?=$this->formLabel($loginForm->get('email'));?>
                    <?=$this->formEmail($loginForm->get('email'));?>
                    <?=$this->formElementErrors($loginForm->get('email'));?>
                </div>

                <div class="form-group pb-1 pt-3 pl-3 pr-3 mb-2">
                    <?=$this->formLabel($loginForm->get('password'));?>
                    <?=$this->formPassword($loginForm->get('password'));?>
                    <?=$this->formElementErrors($loginForm->get('password'));?>
                </div>

                <div class="form-group mb-3 mt-1">
                    <?=$this->formCheckbox($loginForm->get('remember_me'));?>
                    <?=$this->formLabel($loginForm->get('remember_me'));?>
                </div>

                <div class="form-group">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                </div>

                <div class="hidden">
                    <?=$this->formElement($loginForm->get('security'));?>
                </div>

                <?=$this->formElementErrors($loginForm->get('security'));?>

            <?php endif; ?>
        </div>
    </div>
</div>
