credentials:
    database:
        local_adapter:
            driver:   driver_replace
            dsn:      mysql:dbname=dsn_dbname_replace;host=dsn_host_replace;
            dbname:   dbname_replace
            dbhost:   dbhost_replace
            dbuser: dbuser_replace
            dbpassword: dbpassword_replace
    modules:
        jsonrates:
            apikey:   jsonrates_apikey_replace