<?php

$form->prepare();

?>

    <?=$this->form()->openTag($form);?>

        <div class="form-group p-3">
            <?=$this->formLabel($form->get('stock_qty'));?>
            <?=$this->formNumber($form->get('stock_qty'));?>
            <?=$this->formElementErrors($form->get('stock_qty'));?>
        </div>
        <div class="form-group bg-light p-3">
            <?=$this->formLabel($form->get('stock_barcode'));?>
            <?=$this->formInput($form->get('stock_barcode'));?>
            <?=$this->formElementErrors($form->get('stock_barcode'));?>
        </div>

        <hr />

        <div class="form-group">
            <?=$this->formSubmit($form->get('submit'));?>
        </div>
        <div class="hidden">
            <?=$this->formElement($form->get('application_id'));?>
            <?=$this->formElement($form->get('csrf'));?>
        </div>

        <?=$this->formElementErrors($form->get('application_id'));?>
        <?=$this->formElementErrors($form->get('csrf'));?>

    <?=$this->form()->closeTag();?>