<?php
$form->prepare();
?>

    <?=$this->form()->openTag($form);?>

        <div class="form-group pb-1 pt-3 pl-3 pr-3 mb-0">
            <?=$this->formLabel($form->get('stock_qty'));?>
            <?=$this->formNumber($form->get('stock_qty'));?>
            <?=$this->formElementErrors($form->get('stock_qty'));?>
        </div>
        <div class="form-group px-3 py-0">
            <?=$this->formCheckbox($form->get('keep_qty'));?>
            <?=$this->formLabel($form->get('keep_qty'));?>
            <?=$this->formElementErrors($form->get('keep_qty'));?>
        </div>
        <div class="form-group bg-light p-3">
            <?=$this->formLabel($form->get('stock_barcode'));?>
            <?=$this->formInput($form->get('stock_barcode'));?>
            <?=$this->formElementErrors($form->get('stock_barcode'));?>
        </div>

        <hr />

        <div class="form-group">
            <?=$this->formSubmit($form->get('submit'));?>
        </div>
        <div class="hidden">
            <?=$this->formElement($form->get('application_id'));?>
            <?=$this->formElement($form->get('csrf'));?>
        </div>

        <?=$this->formElementErrors($form->get('application_id'));?>
        <?=$this->formElementErrors($form->get('csrf'));?>

    <?=$this->form()->closeTag();?>