<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Restaurant Booking System</h1>
            <hr />
            <h3>Choose your app</h3>
            <p>
                <a href="<?=$this->url('resto.landing.pricing');?>" class="btn btn-light btn-lg my-2">Restaurant</a>
                <a href="<?=$this->url('resto.landing.pricing');?>" class="btn btn-light btn-lg my-2">Restable</a>
                <a href="<?=$this->url('resto.start.guest');?>" class="btn btn-primary btn-lg my-2">Guest</a>
                <a href="<?=$this->url('resto.admin.login.get');?>" class="btn btn-secondary btn-lg my-2">Admin</a>
            </p>
        </div>
    </section>

</main>
