<style>

    bdody {
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#cbebff+0,f0f9ff+8,f0f9ff+49,f0f9ff+49,f0f9ff+84,a1dbff+100 */
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#275ea3+0,f0f9ff+8,f0f9ff+49,f0f9ff+49,f0f9ff+84,275ea3+100 */
        background: #DFE8F2; /* Old browsers */
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f0f9ff+8,f0f9ff+49,dfe8f2+49,f0f9ff+84 */
        background: #f0f9ff; /* Old browsers */
        background: -moz-linear-gradient(top, #f0f9ff 8%, #f0f9ff 49%, #dfe8f2 49%, #f0f9ff 84%); /* FF3.6-15 */
        background: -webkit-linear-gradient(top, #f0f9ff 8%,#f0f9ff 49%,#dfe8f2 49%,#f0f9ff 84%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to bottom, #f0f9ff 8%,#f0f9ff 49%,#dfe8f2 49%,#f0f9ff 84%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f0f9ff', endColorstr='#f0f9ff',GradientType=0 ); /* IE6-9 */

        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f0f9ff+8,dfe8f2+96 */
        background: #f0f9ff; /* Old browsers */
        background: -moz-radial-gradient(center, ellipse cover, #f0f9ff 8%, #dfe8f2 96%); /* FF3.6-15 */
        background: -webkit-radial-gradient(center, ellipse cover, #f0f9ff 8%,#dfe8f2 96%); /* Chrome10-25,Safari5.1-6 */
        background: radial-gradient(ellipse at center, #f0f9ff 8%,#dfe8f2 96%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f0f9ff', endColorstr='#dfe8f2',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
    }

    body {
        background: #f0f9ff;
        background: #1a8c6b;
    }
    #landing-header-bg-1
    {
        -webkit-box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.08);
        -moz-box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.08);
        box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.08);
    /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#1e5799+0,212b97+92,212b97+97,212b97+100 */
        background:#139974;
        background-color: #139974;
        background-color: #139974;
        background-image: url("data:image/svg+xml,%3Csvg width='12' height='24' viewBox='0 0 12 24' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%2300946b' fill-opacity='0.4'%3E%3Cpath d='M2 0h2v12H2V0zm1 20c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zM9 8c1.105 0 2-.895 2-2s-.895-2-2-2-2 .895-2 2 .895 2 2 2zm-1 4h2v12H8V12z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
        /*background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='4' height='4' viewBox='0 0 4 4'%3E%3Cpath fill='%2300946b' fill-opacity='0.4' d='M1 3h1v1H1V3zm2-2h1v1H3V1z'%3E%3C/path%3E%3C/svg%3E");*/
        /*background: -moz-radial-gradient(center, ellipse cover, #1e5799 0%, #212b97 92%, #212b97 97%, #212b97 100%); !* FF3.6-15 *!*/
        /*background: -webkit-radial-gradient(center, ellipse cover, #1e5799 0%,#212b97 92%,#212b97 97%,#212b97 100%); !* Chrome10-25,Safari5.1-6 *!*/
        /*background: radial-gradient(ellipse at center, #1e5799 0%,#212b97 92%,#212b97 97%,#212b97 100%); !* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ *!*/
        /*filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#1e5799', endColorstr='#212b97',GradientType=1 ); !* IE6-9 fallback on horizontal gradient *!*/

    }

    #landing-header-bg-2a  {
        background:#139974;
    }

    button.btn,
    #landing-header-bg-1 h1,
    #landing-header-bg-2 h2 {
        font-family: 'Titillium Web', sans-serif;
    }
    #landing-header-bg-3 h1,
    .card-header h4,
    #landing-header-bg-2 h2 {
        font-family: 'Fira Sans';
        -webkit-box-shadow: 0px 0px 39px -37px rgba(0,0,0,1.2);
        -moz-box-shadow: 0px 0px 39px -37px rgba(0,0,0,1.2);
        box-shadow: 0px 0px 39px -37px rgba(0,0,0,1.2);
    }

    p,
    #landing-header-bg-2 li {
        font-family: 'Lato', sans-serif;
    }
    #landing-header-bg-2 li .fa {
        margin-right:7px;
    }
    #landing-header-bg-2 li {
        margin-bottom:3px;
    }

    #landing-header-bg-1 h1,
    #landing-header-bg-1 p {
        background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxkZWZzPjxsaW5lYXJHcmFkaWVudCBpZD0iZ3JhZGllbnQiIHgxPSIwJSIgeTE9IjAlIiB4Mj0iMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojRkZGRkZGOyIgLz48c3RvcCBvZmZzZXQ9IjEwMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiNFOEU4RTg7IiAvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IGZpbGw9InVybCgjZ3JhZGllbnQpIiBoZWlnaHQ9IjEwMCUiIHdpZHRoPSIxMDAlIiAvPjwvc3ZnPg==);
        background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #FFFFFF), color-stop(100%, #E8E8E8));
        background-image: -moz-linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        background-image: -webkit-linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        background-image: -o-linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        background-image: -ms-linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        background-image: linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        position:relative;
        display:inline-block; /*required*/
    }
    #landing-header-bg-2 {
        -webkit-box-shadow: inset 0px 0px 199px 0px rgba(0,0,0,0.2);
        -moz-box-shadow: inset 0px 0px 199px 0px rgba(0,0,0,0.2);
        box-shadow: inset 0px 0px 199px 0px rgba(0,0,0,0.2);
        border-top: 2px solid #e6e6e6;
    }
    #landing-header-bg-3 {
        background:#139974;
        background-color:#d7dfe5;
        border-radius:0px;
        border-top: 2px solid #e6e6e6;
    }
    main .card-deck .card-hseader {
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f0f9ff+8,f0f9ff+49,dfe8f2+49,f0f9ff+84 */
        background: #f0f9ff; /* Old browsers */
        background: -moz-linear-gradient(top, #f0f9ff 8%, #f0f9ff 49%, #dfe8f2 49%, #f0f9ff 84%); /* FF3.6-15 */
        background: -webkit-linear-gradient(top, #f0f9ff 8%,#f0f9ff 49%,#dfe8f2 49%,#f0f9ff 84%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to bottom, #f0f9ff 8%,#f0f9ff 49%,#dfe8f2 49%,#f0f9ff 84%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f0f9ff', endColorstr='#f0f9ff',GradientType=0 ); /* IE6-9 */
    }
    main .card-body {
        -webkit-box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.01);
        -moz-box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.01);
        box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.01);
    }
    .card {
        -webkit-box-shadow: 0px 0px 139px -37px rgba(0,0,0,0.2);
        -moz-box-shadow: 0px 0px 139px -37px rgba(0,0,0,0.2);
        box-shadow: 0px 0px 139px -37px rgba(0,0,0,0.2);
    }
    .form-container-wrapper .form-title {
        font-family: 'Titillium Web', sans-serif;
        color:#666;
    }
</style>
<style>
    .form-container-wrapper {
        transition-property: height;
        -webkit-box-shadow: inset 0 0 5px 0 rgba(0,0,0,.05);
        -moz-box-shadow: inset 0 0 5px 0 rgba(0,0,0,.05);
        box-shadow: inset 0 0 20px 10px rgba(0,0,0,.05);
        background: #fff;
        background: -moz-radial-gradient(center,ellipse cover,#fff 0,#f0f0ec 100%);
        background: -webkit-radial-gradient(center,ellipse cover,#fff 0,#f0f0ec 100%);
        background: radial-gradient(ellipse at center,#fff 0,#f0f0ec 100%);
    }
</style>
    <div id="landing-header-bg-1" class="position-relative overflow-hidden p-3 p-md-5 m-0 my-5 pb-10 text-left">
        <div class="container">
            <div class="row justify-content-around h-100 mx-auto">
                <div class="col-12 col-md-6 p-lg-5 mx-0 my-0">
                    <h1 style="color:#fefefe" class="mb-0 display-4 font-weight-normal">Request Demo Access</h1>
                    <hr class="pb-1" />
                    <p style="color:#fefefe" class="lead font-weight-normal">After the approval proccess we will send you the link to the demo app.</p>
                    <p style="color:#fefefe" class="lead font-weight-normal"><strong>In short:</strong> We will send you the email with login credentials. The access will be granted for 72 hours from the first login. The link will be valid for 7 days.</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4 offset-md-2 mt-sm-2 mt-md-0 p-2 my-0 pt-sm-4 bg-light rounded form-container-wrapper">
                    <h3 class="display-5 form-title text-center">Demo Request Form</h3>
                    <?=$this->getFormAttached($forms,null,'form_request_demo',true,'restablesite-staticpages-form::page-request-demo-form');?>
                </div>
            </div>
        </div>
    </div>
