
    <style>
        /* Make the image fully responsive */
        .carousel-inner img {
            width: 100%;
            height: 100%;
        }
        .container-features h1,
        .container-features h2,
        .container-features h3 {
            color: #333;
        }
        .container-features span {
            text-shadow: 1px 1px #eee;
        }
        .row-features i {
            font-size:1.6rem;
            margin-right:5px;
            /*color: #CD6E22;*/
        }
    </style>

<div class="container container-features">

    <div class="row">
        <div class="col-12">
            <h3 class="display-4 text-center mb-5 text-dark">Stock Monitoring</h3>
        </div>
    </div>

    <div class="row row-features">
        <div class="col-4">
            <h2>
                <i class="fas fa-barcode align-middle"></i>
                <span class="d-inline-block align-middle">Low Level Alert</span>
            </h2>
            <p>Trysail Sail ho Corsair red ensign hulk smartly boom jib rum gangway. Case shot Shiver me timbers gangplank crack Jennys tea cup ballast Blimey lee snow crow's nest rutters. </p>
        </div>
        <div class="col-4">
            <h2>
                <i class="far fa-calendar-alt align-middle"></i>
                <span class="d-inline-block align-middle">Periodical Reports</span>
            </h2>
            <p>Deadlights jack lad schooner scallywag dance the hempen jig carouser broadside cable strike colors. Bring a spring upon her cable holystone blow the man down spanker Shiver me timbers to go on account lookout wherry doubloon chase. </p>
        </div>
        <div class="col-4">
            <h2>
                <i class="fas fa-barcode align-middle"></i>
                <span class="d-inline-block align-middle">Barcode Scanning</span>
            </h2>
            <p>Booty rutters Cat o'nine tails cutlass Plate Fleet ballast Nelsons folly mizzen bilge water strike colors. Belaying pin grog blossom deadlights lanyard jury mast rutters sheet Chain Shot knave coffer. </p>
        </div>
    </div>

    <div class="row row-features">
        <div class="col-4">
            <h2>
                <i class="far fa-calendar-alt align-middle"></i>
                <span class="d-inline-block align-middle">Live Monitoring</span>
            </h2>
            <p>Deadlights jack lad schooner scallywag dance the hempen jig carouser broadside cable strike colors. Bring a spring upon her cable holystone blow the man down spanker Shiver me timbers to go on account lookout wherry doubloon chase. </p>
        </div>
        <div class="col-4">
            <h2>
                <i class="fas fa-barcode align-middle"></i>
                <span class="d-inline-block align-middle">Custom Labels</span>
            </h2>
            <p>Trysail Sail ho Corsair red ensign hulk smartly boom jib rum gangway. Case shot Shiver me timbers gangplank crack Jennys tea cup ballast Blimey lee snow crow's nest rutters. </p>
        </div>
        <div class="col-4">
            <h2>
                <i class="fas fa-barcode align-middle"></i>
                <span class="d-inline-block align-middle">Bulk Products</span>
            </h2>
            <p>Booty rutters Cat o'nine tails cutlass Plate Fleet ballast Nelsons folly mizzen bilge water strike colors. Belaying pin grog blossom deadlights lanyard jury mast rutters sheet Chain Shot knave coffer. </p>
        </div>
    </div>

</div>
