
    <style>
        /* Make the image fully responsive */
        .carousel-inner img {
            width: 100%;
            height: 100%;
        }
        .container-features h1,
        .container-features h2,
        .container-features h3 {
            color: #CD6E22;
        }
    </style>

<div id="demo" class="carousel slide" data-ride="carousel">
    <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
    </ul>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="position-relative overflow-hidden p-3 p-md-0 m-md-0 text-center bg-light">
                <div class="col-md-5 p-lg-5 mx-auto my-5">
                    <h1 class="display-4 font-weight-normal">Punny headline</h1>
                    <p class="lead font-weight-normal">And an even wittier subheading to boot. Jumpstart your marketing efforts with this example based on Apple's marketing pages.</p>
                    <a class="btn btn-outline-secondary" href="#">Coming soon</a>
                </div>
                <div class="product-device box-shadow d-none d-md-block"></div>
                <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="position-relative overflow-hidden p-3 p-md-0 m-md-0 text-center bg-light">
                <div class="col-md-5 p-lg-5 mx-auto my-5">
                    <h1 class="display-4 font-weight-normal">Punny headline</h1>
                    <p class="lead font-weight-normal">And an even wittier subheading to boot. Jumpstart your marketing efforts with this example based on Apple's marketing pages.</p>
                    <a class="btn btn-outline-secondary" href="#">Coming soon</a>
                </div>
                <div class="product-device box-shadow d-none d-md-block"></div>
                <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
            </div>
        </div>
        <div class="carousel-item">
            <div class="position-relative overflow-hidden p-3 p-md-0 m-md-0 text-center bg-light">
                <div class="col-md-5 p-lg-5 mx-auto my-5">
                    <h1 class="display-4 font-weight-normal">Punny headline</h1>
                    <p class="lead font-weight-normal">And an even wittier subheading to boot. Jumpstart your marketing efforts with this example based on Apple's marketing pages.</p>
                    <a class="btn btn-outline-secondary" href="#">Coming soon</a>
                </div>
                <div class="product-device box-shadow d-none d-md-block"></div>
                <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>
</html>

<div class="container container-features">
    <div class="row">
        <div class="col-12">
            <h3 class="display-4 text-center mb-5 text-dark">Features</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <h2>Online Booking</h2>
            <p>Deadlights jack lad schooner scallywag dance the hempen jig carouser broadside cable strike colors. Bring a spring upon her cable holystone blow the man down spanker Shiver me timbers to go on account lookout wherry doubloon chase. </p>
        </div>
        <div class="col-4">
            <h2>Point of Sale</h2>
            <p>Trysail Sail ho Corsair red ensign hulk smartly boom jib rum gangway. Case shot Shiver me timbers gangplank crack Jennys tea cup ballast Blimey lee snow crow's nest rutters. </p>
        </div>
        <div class="col-4">
            <h2>Business Website</h2>
            <p>Booty rutters Cat o'nine tails cutlass Plate Fleet ballast Nelsons folly mizzen bilge water strike colors. Belaying pin grog blossom deadlights lanyard jury mast rutters sheet Chain Shot knave coffer. </p>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <h2>Email Templates</h2>
            <p>Hands league handsomely Chain Shot scallywag brigantine piracy hang the jib overhaul scuppers. Rutters yardarm Jack Tar booty pinnace Letter of Marque long boat matey Blimey no prey, no pay. </p>
        </div>
        <div class="col-4">
            <h2>Stock Monitoring</h2>
            <p>Prow scuttle parrel provost Sail ho shrouds spirits boom mizzenmast yardarm. Pinnace holystone mizzenmast quarter crow's nest nipperkin grog yardarm hempen halter furl. </p>
        </div>
        <div class="col-4">
            <h2>Integrated Admin Panel</h2>
            <p>Bucko scourge of the seven seas rutters yardarm draught barkadeer sutler gangway crimp booty. Tender swing the lead scallywag crow's nest keel ahoy black jack lee nipper lanyard.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <h2>Online Pre-Orders</h2>
            <p>Hands league handsomely Chain Shot scallywag brigantine piracy hang the jib overhaul scuppers. Rutters yardarm Jack Tar booty pinnace Letter of Marque long boat matey Blimey no prey, no pay. </p>
        </div>
        <div class="col-4">
            <h2>Financial Reports</h2>
            <p>Hands league handsomely Chain Shot scallywag brigantine piracy hang the jib overhaul scuppers. Rutters yardarm Jack Tar booty pinnace Letter of Marque long boat matey Blimey no prey, no pay. </p>
        </div>
        <div class="col-4">
            <h2>Mobile Application</h2>
            <p>Bucko scourge of the seven seas rutters yardarm draught barkadeer sutler gangway crimp booty. Tender swing the lead scallywag crow's nest keel ahoy black jack lee nipper lanyard.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-4">
            <h2>Offline data</h2>
            <p>Booty rutters Cat o'nine tails cutlass Plate Fleet ballast Nelsons folly mizzen bilge water strike colors. Belaying pin grog blossom deadlights lanyard jury mast rutters sheet Chain Shot knave coffer. </p>
        </div>
        <div class="col-4">
            <h2>Guest Notes</h2>
            <p>Booty rutters Cat o'nine tails cutlass Plate Fleet ballast Nelsons folly mizzen bilge water strike colors. Belaying pin grog blossom deadlights lanyard jury mast rutters sheet Chain Shot knave coffer. </p>
        </div>
        <div class="col-4">
            <h2>Wordpress Integration</h2>
            <p>Bucko scourge of the seven seas rutters yardarm draught barkadeer sutler gangway crimp booty. Tender swing the lead scallywag crow's nest keel ahoy black jack lee nipper lanyard.</p>
        </div>
    </div>
</div>

<!--            <svg xmlns="http://www.w3.org/2000/svg" width="250" height="250" viewBox="0 0 250 25s0" fill="none" stroke="currentColor" stroke-width="20" stroke-linecap="round" stroke-linejoin="round" class="d-inline mx-auto">-->
<!--                <circle cx="120" cy="120" r="100"></circle>-->
<!--                <line x1="143.1" y1="80" x2="200.5" y2="179.4"></line>-->
<!--                <line x1="96.9" y1="80" x2="211.7" y2="80"></line>-->
<!--                <line x1="73.8" y1="120" x2="131.2" y2="20.6"></line>-->
<!--                <line x1="96.9" y1="160" x2="39.5" y2="60.6"></line>-->
<!--                <line x1="143.1" y1="160" x2="28.3" y2="160"></line>-->
<!--                <line x1="166.2" y1="120" x2="108.8" y2="219.4"></line>-->
<!--            </svg>-->
