<style>

    bdody {
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#cbebff+0,f0f9ff+8,f0f9ff+49,f0f9ff+49,f0f9ff+84,a1dbff+100 */
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#275ea3+0,f0f9ff+8,f0f9ff+49,f0f9ff+49,f0f9ff+84,275ea3+100 */
        background: #DFE8F2; /* Old browsers */
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f0f9ff+8,f0f9ff+49,dfe8f2+49,f0f9ff+84 */
        background: #f0f9ff; /* Old browsers */
        background: -moz-linear-gradient(top, #f0f9ff 8%, #f0f9ff 49%, #dfe8f2 49%, #f0f9ff 84%); /* FF3.6-15 */
        background: -webkit-linear-gradient(top, #f0f9ff 8%,#f0f9ff 49%,#dfe8f2 49%,#f0f9ff 84%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to bottom, #f0f9ff 8%,#f0f9ff 49%,#dfe8f2 49%,#f0f9ff 84%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f0f9ff', endColorstr='#f0f9ff',GradientType=0 ); /* IE6-9 */

        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f0f9ff+8,dfe8f2+96 */
        background: #f0f9ff; /* Old browsers */
        background: -moz-radial-gradient(center, ellipse cover, #f0f9ff 8%, #dfe8f2 96%); /* FF3.6-15 */
        background: -webkit-radial-gradient(center, ellipse cover, #f0f9ff 8%,#dfe8f2 96%); /* Chrome10-25,Safari5.1-6 */
        background: radial-gradient(ellipse at center, #f0f9ff 8%,#dfe8f2 96%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f0f9ff', endColorstr='#dfe8f2',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
    }

    body {
        background: #f0f9ff;
    }
    #landing-header-bg-1
    {
        -webkit-box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.08);
        -moz-box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.08);
        box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.08);
        background: #1e5799; /* Old browsers */
        background: -moz-radial-gradient(center, ellipse cover, #1e5799 0%, #3B5998 92%, #3B5986 100%); /* FF3.6-15 */
        background: -webkit-radial-gradient(center, ellipse cover, #1e5799 0%,#3B5998 92%,#3B5986 100%); /* Chrome10-25,Safari5.1-6 */
        background: radial-gradient(ellipse at center, #1e5799 0%,#3B5998 92%,#3B5986 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#1e5799', endColorstr='#3B5998',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */

    }

    #landing-header-bg-2a  {
        background:#139974;
    }

    button.btn,
    #landing-header-bg-1 h1,
    #landing-header-bg-2 h2 {
        font-family: 'Titillium Web', sans-serif;
    }
    #landing-header-bg-3 h1,
    .card-header h4,
    #landing-header-bg-2 h2 {
        font-family: 'Fira Sans';
        -webkit-box-shadow: 0px 0px 39px -37px rgba(0,0,0,1.2);
        -moz-box-shadow: 0px 0px 39px -37px rgba(0,0,0,1.2);
        box-shadow: 0px 0px 39px -37px rgba(0,0,0,1.2);
    }

    p,
    #landing-header-bg-2 li {
        font-family: 'Lato', sans-serif;
    }
    #landing-header-bg-2 li .fa {
        margin-right:7px;
    }
    #landing-header-bg-2 li {
        margin-bottom:3px;
    }

    #landing-header-bg-1 h1,
    #landing-header-bg-1 p {
        background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjxkZWZzPjxsaW5lYXJHcmFkaWVudCBpZD0iZ3JhZGllbnQiIHgxPSIwJSIgeTE9IjAlIiB4Mj0iMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojRkZGRkZGOyIgLz48c3RvcCBvZmZzZXQ9IjEwMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiNFOEU4RTg7IiAvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IGZpbGw9InVybCgjZ3JhZGllbnQpIiBoZWlnaHQ9IjEwMCUiIHdpZHRoPSIxMDAlIiAvPjwvc3ZnPg==);
        background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #FFFFFF), color-stop(100%, #E8E8E8));
        background-image: -moz-linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        background-image: -webkit-linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        background-image: -o-linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        background-image: -ms-linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        background-image: linear-gradient(top,#FFFFFF 0%,#E8E8E8 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        position:relative;
        display:inline-block; /*required*/
    }
    #landing-header-bg-2 {
        -webkit-box-shadow: inset 0px 0px 199px 0px rgba(0,0,0,0.2);
        -moz-box-shadow: inset 0px 0px 199px 0px rgba(0,0,0,0.2);
        box-shadow: inset 0px 0px 199px 0px rgba(0,0,0,0.2);
        border-top: 2px solid #e6e6e6;
    }
    #landing-header-bg-3 {
        background:#139974;
        background-color:#d7dfe5;
        border-radius:0px;
        border-top: 2px solid #e6e6e6;
    }
    main .card-deck .card-hseader {
        /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f0f9ff+8,f0f9ff+49,dfe8f2+49,f0f9ff+84 */
        background: #f0f9ff; /* Old browsers */
        background: -moz-linear-gradient(top, #f0f9ff 8%, #f0f9ff 49%, #dfe8f2 49%, #f0f9ff 84%); /* FF3.6-15 */
        background: -webkit-linear-gradient(top, #f0f9ff 8%,#f0f9ff 49%,#dfe8f2 49%,#f0f9ff 84%); /* Chrome10-25,Safari5.1-6 */
        background: linear-gradient(to bottom, #f0f9ff 8%,#f0f9ff 49%,#dfe8f2 49%,#f0f9ff 84%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f0f9ff', endColorstr='#f0f9ff',GradientType=0 ); /* IE6-9 */
    }
    main .card-body {
        -webkit-box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.01);
        -moz-box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.01);
        box-shadow: inset 0px 0px 20px 10px rgba(0,0,0,0.01);
    }
    .card {
        -webkit-box-shadow: 0px 0px 139px -37px rgba(0,0,0,0.2);
        -moz-box-shadow: 0px 0px 139px -37px rgba(0,0,0,0.2);
        box-shadow: 0px 0px 139px -37px rgba(0,0,0,0.2);
    }
</style>

<div id="landing-header-bg-1" class="position-relative overflow-hidden p-3 p-md-5 m-0 mb-0 pb-10 text-center hbg-light">
    <div class="col-md-8 p-lg-5 mx-auto my-0">
        <h1 style="color:#fefefe" class="mb-0 display-4 font-weight-normal">Restaurant Management Software</h1>
        <hr class="pb-1" />
        <p style="color:#fefefe" class="lead font-weight-normal">Application Suite developed to support your Business.</p>
    </div>
    <div class="product-device box-shadow d-none d-md-block"></div>
    <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
</div>

<div id="landing-header-bg-2" class="position-relative overflow-hidden p-3 p-md-5 m-0 mb-0 pt-10 pb-10 text-center hbg-light">
    <main class="container mt-20">
        <div class="card-deck mb-5 pt-4 justify-content-around ">
            <h2 class="display-4aa text-left">Monthly Subscription Plans</h2>
        </div>

        <div class="card-deck mb-5 pt-4 text-center justify-content-around ">
            <div class="card mb-4 px-0 col-md-3 shadow-lg">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Basic</h4>
                </div>
                <div class="card-body shadow-lg">
                    <h1 class="card-title pricing-card-title">£19 <small class="text-muted">/ mo</small></h1>
                    <ul class="list-unstyled mt-3 mb-4 text-left">
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Online Table Reservations</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Table Management</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Email and SMS Communication</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Daily Data Backup</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Unlimited Reservations</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Support</li>
                    </ul>
                </div>
                <div class="card-footer text-muted">
                    <a href="<?=$this->url('restable.site.page.request_demo');?>" type="button" class="btn btn-lg btn-block btn-success">Get started</a>
                </div>
            </div>
            <div class="card mb-4 px-0 col-md-3 col-offset-1 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Small</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">£39 <small class="text-muted">/ mo</small></h1>
                    <ul class="list-unstyled mt-3 mb-4 text-left">
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Online Table Reservations</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Table Management</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Point of Sale</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Stock Monitoring</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Email and SMS Communication</li>

                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Unlimited Reservations</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Email support</li>
                    </ul>
                </div>
                <div class="card-footer text-muted">
                    <a href="<?=$this->url('restable.site.page.request_demo');?>" type="button" class="btn btn-lg btn-block btn-success">Get started</a>
                </div>
            </div>
            <div class="card mb-4 px-0 col-3 col-offset-1 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Medium</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">£99 <small class="text-muted">/ mo</small></h1>
                    <ul class="list-unstyled mt-3 mb-4 text-left">
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Online Table Reservations</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Table Management</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Point of Sale</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i><strong>Live</strong> Stock Monitoring</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Email and SMS Communication</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Website with Templates</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Unlimited Reservations</li>
                        <li><i class="fa fa-angle-right" aria-hidden="true"></i>Email support</li>
                    </ul>
                </div>
                <div class="card-footer text-muted">
                    <a href="<?=$this->url('restable.site.page.request_demo');?>" type="button" class="btn btn-lg btn-block btn-secondary disabled">Coming Soon</a>
                </div>
            </div>
        </div>
    </main>
</div>

    <div id="landing-header-bg-3" class="bg-darsk jumbotron mb-0">
        <div class="container mt-20">
            <div  class="row">
                <div class="col-6 p-lg-5 mx-auto my-0">
                    <h1 style="color:#444" class="mb-0 display-4 font-weight-normal">One Month Trial</h1>
                    <p style="color:#fefefe" class="lead font-weight-normal text-muted">Get started with a no obligation free trial.</p>
                </div>
                <div class="col-6 p-lg-5 mx-auto my-0 text-center">
                    <a href="<?=$this->url('restable.site.page.request_demo');?>" style="background: #F6B44A" class="btn btn-lg btn-warning">Get Started</a>
                </div>
            </div>

        </div>

    </div>

