<div class="container mt-4">
    <div class="row">
        <div class="col-12">
            <h1>Privacy Policy</h1>
            <p>This Privacy Policy (or "Policy") describes the ways in which Rogue Wave Software, Inc. (together with its affiliates "Company" or "we") collect, use, process, and disclose information that we collect from you or that you may provide when you visit any website on which this Policy is posted. We may have different policies for other sites and products, so please always check for the applicable policy on any of our sites you may use. Also, please note that this Policy does not apply to information collected by us offline or through any other means, including when you use one of our products or services.</p>
            <p>Please read this Policy carefully before sharing information with us. By using the website on which this Policy is posted, you agree to the terms of this Policy and our use, sharing and disclosure of information as described below including any revisions to this Policy. If you do not agree with the practices described in this Policy, you may chose not to use this website. In the event of any conflict between this Policy and either (1) a specific contract we have with you, if any; (2) applicable law, the terms of items (1) and (2) will control over this Policy, and this Policy shall be deemed amended to conform to such other items.</p>

            <h3>Information we may collect about you and how we collect it</h3>

            <p>We collect two kinds of information, personal information that can be used to identify you, and non-personal information.</p>
            <p>In general, you can visit this website without telling us who you are or revealing any personal information. There are times, however, when we may gather information from you that you provide voluntarily. The types of personal information we collect about you that can be used to identify you as an individual person including things like your name, address, email address, country of residence, the company you work for, and phone number.</p>
            <p>We also collect non-personal information when you use our website, such as information about your internet connection, the equipment you use to access our website, and usage details, and search queries submitted on our website.</p>
            <p>We collect personal information directly from you when you provide it to us by, for example, filling out the forms on our website, communicating with us via email, or submitting search queries on the website.</p>
            <p>We also may collect non-personal information automatically as you navigate through the site through the use of technology such as cookies, flash cookies, and web beacons. Using this kind of technology, our web servers automatically recognize and collect the domain name and IP address of visitors to our website. This kind of technology may transfer data to your browser that can be read by us as a sort of a non-personal identification card, recording information about your past visits to our website. It also can be combined with personal information. In addition, we collect aggregate information on web page visits.</p>
            <p>We do not respond to "do-not-track" signals or other mechanisms that allow users to signal their preferences on the collection of their personal information over time and across third-party websites or online services. This website does not monitor for or adjust any use as the result of "do-not-track" signals.</p>

            <h3>How we use the information we collect</h3>
            <p>We may use the information we collect about you, including your personal information, to:</p>
            <ul>
                <li>Present the website and its content to you;</li>
                <li>Provide you with information, products, or services that you request from us and optimize your experience on our website;</li>
                <li>Provide customer support, permit product evaluations, or otherwise manage our relationship with you or your company;</li>
                <li>Notify you about changes to our website or any products or services we offer;</li>
                <li>Communicate with you by e-mail, postal mail, telephone, or mobile device about our products, services, industry issues, and upcoming events;</li>
                <li>Perform research and analysis about your use of, or interest in, our products, services, or website;</li>
                <li>Update and improve our services;</li>
                <li>Perform other functions as otherwise described to you at the time of collection; and</li>
            </ul>

            <h3>Disclosure of your information</h3>
            <p>We may disclose or share your information, including personal information:</p>
            <ul>
                <li>With our subsidiaries and affiliated companies, companies with which we have a strategic relationship;</li>
                <li>With other companies that perform work necessary for Rogue Wave (but only to allow them to provide products and services for us);</li>
                <li>For any other purpose disclosed by us when you provide the information;</li>
                <li>To a successor, if all or part of our business is sold, merged, dissolved, acquired, reorganized or subject to a similar transaction; and</li>
                <li>As necessary to comply with a subpoena or similar investigative demand, court order, request for cooperation from law enforcement or other governmental agency, to exercise our legal rights, to defend against legal claims, to protect someone's safety, or as otherwise required by law.</li>
            </ul>

            <h3>Your choices about collection and use of your information</h3>
            <p>You can chose not to provide us with certain information, but that may result in you being unable to use certain features of our website, request information about products or services, purchase products and services, ask questions, or initiate other transactions on our website. You also can set your browser to notify you when you receive a cookie, giving you the chance to accept or reject it. And you can opt out of receiving emails from us by clicking the "unsubscribe" link in any email you receive from us. We also have a preference center to indicate your areas of interest and to control our outreach to you.</p>

            <h3>How we protect your personal information</h3>
            <p>We take appropriate security measures (including physical, technical, and administrative measures) to help safeguard your personal information from unauthorized access and disclosure. No system, however, can be completely secure. While we take steps to secure your personal information, we do not promise that your personal information, searches, or other questions will always remain secure. We are not responsible or liable for the illegal acts (such as hacking) by third parties. If you have concerns about the security of your personal information, please contact us at legal@roguewave.com.</p>

            <h3>Links to other sites</h3>
            <p>Our websites may contain links to the sites of other companies. Rogue Wave is not responsible for their privacy practices. We encourage you to learn about the privacy policies of those companies before sharing information.</p>

            <h3>Children's privacy</h3>
            <p>Our website is a general audience site and is not directed at, or intended for use by, children under 13. Accordingly, we do not knowing collect personal information from children under the age of 13.</p>

            <h3>International visitors</h3>
            <p>If you are located outside the United States, you understand and agree that information you provide via one of our websites may be sent to and processed by computers located in the United States.</p>

            <h3>Changes to this privacy policy</h3>
            <p>If there are updates to this Policy, we will post those changes here and update the revision date so you will always know what information we collect, how we use it, and what choices you have. Continued use of this website after any changes is deemed to be acceptance of those changes. Accordingly, we encourage you to check the Policy periodically for updates. Please note that this Policy was changed on February 13, 2018 to better enable customers to understand how personal information is collected, used and shared.</p>

            <h3>How to contact us</h3>
            <p>If you have any questions about this Policy or our information-handling practices, please contact us at privacy@roguewave.com.</p>
        </div>
        <hr />
        <div class="col-12">
            <h1>POLITYKA PRYWATNOŚCI</h1>
            <small>Serwis Wykop.pl szanuje prywatność swoich użytkowników. Przeczytaj dokładnie poniższe informacje, aby lepiej zapoznać się z naszą polityką prywatności.</small>

            <h3>Artykuł 1. Zasada ochrony prywatności</h3>
            <ol>
                <li>Administratorem danych osobowych jest Wykop Sp. z o.o. z siedzibą w Poznaniu (60-351 Poznań, ul. Zakręt 8), wpisana do rejestru przedsiębiorców prowadzonego przez Sąd Rejonowy w Poznaniu XXI Wydział Gospodarczy Krajowego Rejestru Sądowego pod numerem KRS 0000280651, o kapitale zakładowym w wysokości 600 000,00 PLN,<li></li>
                <li>Administrator danych osobowych przykłada dużą wagę do ochrony prywatności i poufności danych osobowych użytkowników serwisu wykop.pl dostępnego pod adresem https://www.wykop.pl/ (zwanego dalej: „wykop.pl” lub „Serwisem”).</li>
                <li>Kontakt z Inspektorem Ochrony Danych odbywa się poprzez adres e-mail iodo@wykop.pl</li>
                <li>Administrator z należytą starannością dobiera i stosuje odpowiednie środki techniczne i organizacyjne zapewniające ochronę przetwarzanych danych osobowych. Pełen dostęp do baz danych posiadają jedynie osoby należycie uprawnione przez Administratora.</li>
                <li>Administrator zabezpiecza dane osobowe przed ich udostępnieniem osobom nieupoważnionym, jak również przed ich przetwarzaniem z naruszeniem obowiązujących przepisów prawa.</li>
                <li>Osoby odwiedzające wykop.pl mogą przeglądać treści umieszczone w Serwisie bez podawania danych osobowych.</li>
            </ol>
                Artykuł 2. Podstawa przetwarzania danych osobowych
            Dane osobowe są przetwarzane przez Administratora zgodnie z przepisami prawa, w tym w szczególności z Rozporządzeniem Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 roku w sprawie ochrony osób fizycznych w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (zwanym dalej „GDPR”) w celu:
            zawarcia i wykonania umowy zawartej na warunkach określonych w regulaminie Serwisu (na podstawie art. 6 ust. 1 lit. b GDPR);
            udzielania odpowiedzi użytkownikom Internetu na pytania związane z Serwisem oraz jego funkcjonowaniem (na podstawie art. 6 ust. 1 lit. f GDPR);
            korzystania z usługi newsletter, obejmującej przesyłanie informacji handlowych, na podstawie wyrażonej zgody (art. 6 ust. 1 lit. a GDPR);
            wypełnienia prawnie ciążących obowiązków na Administratorze danych, na podstawie art. 6 ust. 1 lit. c RODO (np. obowiązki rachunkowe i podatkowe);
            dochodzenia lub zabezpieczenia roszczeń (na podstawie art. 6 ust. 1 lit. f GDPR).
            Podanie danych osobowych jest dobrowolne, jednakże konsekwencją niepodania danych może być, w zależności od przypadku, niemożność korzystania z usług świadczonych przez wykop.pl, niemożność uzyskania odpowiedzi na zadane pytania lub niemożność otrzymania newsletter.
            Użytkownik nie powinien przekazywać Administratorowi danych osobowych osób trzecich. Jeżeli natomiast przekazuje takie dane każdorazowo oświadcza, że posiada stosowną zgodę osób trzecich na przekazanie danych Administratorowi.
            Artykuł 3. Zakres przetwarzania danych osobowych
            Administrator przetwarza zakres danych podanych przez użytkownika w treści zagadnienia kierowanego do Administratora.
            Dane podawane przez użytkowników wykorzystywane są jedynie do: realizacji umowy zawartej na warunkach określonych w regulaminie Serwisu, udzielania odpowiedzi na zadawane pytania, przesyłania newsletter, w tym informacji handlowych o Administratorze i jego produktach oraz usługach oraz w celach statystycznych.
            Administrator wykorzystuje adresy IP zbierane w trakcie połączeń internetowych w celach technicznych, związanych z administracją serwerami. Ponadto adresy IP służą do zbierania ogólnych, statystycznych informacji demograficznych (np. o regionie, z którego następuje połączenie).
            Artykuł 4. Kontrola przetwarzania danych osobowych
            Użytkownik jest zobowiązany do wskazywania danych pełnych, aktualnych i prawdziwych.
            Każdy użytkownik, którego dane osobowe są przetwarzane przez Administratora ma prawo dostępu do treści swoich danych oraz prawo ich sprostowania, usunięcia, ograniczenia przetwarzania, prawo do przenoszenia danych, prawo wniesienia sprzeciwu wobec przetwarzania danych na podstawie uzasadnionego interesu Administratora, prawo do cofnięcia zgody w dowolnym momencie bez wpływu na zgodność z prawem przetwarzania (jeżeli przetwarzanie odbywa się na podstawie zgody), którego dokonano na podstawie zgody przed jej cofnięciem.
            Skorzystanie z uprawnień określonych w ustępie powyżej może być realizowane poprzez wysłanie na adres iodo@wykop.pl stosownego żądania wraz z podaniem imienia i nazwiska oraz adresu poczty elektronicznej (e-mail) użytkownika.
            Użytkownik posiada prawo wniesienia skargi do organu nadzorczego, w przypadku gdy uzna, że przetwarzanie jego danych osobowych narusza przepisy GDPR.
            Artykuł 5. Udostępnianie danych osobowych
            Dane użytkowników mogą być udostępniane podmiotom uprawnionym do ich otrzymania na mocy obowiązujących przepisów prawa, w tym właściwym organom wymiaru sprawiedliwości. Dane osobowe mogą być przekazywane podmiotom przetwarzającym je na zlecenie Administratora, to jest agencjom marketingowym, partnerom świadczącym usługi techniczne (rozwijanie i utrzymywanie systemów informatycznych i serwisów internetowych). Dane osobowe nie będą przekazywane do państwa trzeciego/organizacji międzynarodowej.

            Artykuł 6. Okres przechowywania i pozostałe informacje dotyczące przetwarzania danych
            Dane osobowe będą przechowywane tylko przez okres niezbędny do zrealizowania określonego celu, w którym zostały przesłane albo na potrzeby zachowania zgodności z przepisami prawa.
            Jeżeli użytkownik wyraził zgodę na wykorzystanie danych osobowych w związku z korzystaniem z usługi newsletter, dane osobowe będą przetwarzane do czasu odwołania zgody.
            Dane osobowe nie będą przetwarzane w sposób zautomatyzowany przez Administratora.
        </div>
    </div>
</div>