<?php

$form->prepare();

?>
<div class="form-container <?=($form->getMessages())?'has-errors':null;?>">

    <?=$this->form()->openTag($form);?>

        <div class="container pt-2">
            <div class="row">
                <div class="col-6 py-2 px-3">
                    <?=$this->formInput($form->get('name_first'));?>
                    <?=$this->formElementErrors($form->get('name_first'));?>
                </div>
                <div class="col-6 py-2 px-3">
                    <?=$this->formInput($form->get('name_last'));?>
                    <?=$this->formElementErrors($form->get('name_last'));?>
                </div>
            </div>
        </div>

        <div class="py-2 px-3">
            <?=$this->formInput($form->get('contact_phone'));?>
            <?=$this->formElementErrors($form->get('contact_phone'));?>
        </div>
        <div class="py-2 px-3">
            <?=$this->formInput($form->get('contact_email'));?>
            <?=$this->formElementErrors($form->get('contact_email'));?>
        </div>
        <div class="py-2 px-3">
            <?=$this->formInput($form->get('venue_name'));?>
            <?=$this->formElementErrors($form->get('venue_name'));?>
        </div>
        <div class="py-2 px-3">
            <?=$this->formSelect($form->get('work_title'));?>
            <?=$this->formElementErrors($form->get('work_title'));?>
        </div>
        <div class="py-2 px-3">
            <?=$this->formSelect($form->get('country'));?>
            <?=$this->formElementErrors($form->get('country'));?>
        </div>

        <div class="text-right pt-2 pr-3">
            <a href="<?=$this->url('restable.site.page.privacy_policy')?>">Privacy Policy</a>
        </div>
        <hr />

        <div class="py-2 px-3 mb-2">
            <?=$this->formSubmit($form->get('submit'));?>
        </div>

        <div class="hidden">
            <?=$this->formElement($form->get('application_id'));?>
            <?=$this->formElement($form->get('csrf'));?>
        </div>

        <?=$this->formElementErrors($form->get('application_id'));?>
        <?=$this->formElementErrors($form->get('csrf'));?>

    <?=$this->form()->closeTag();?>

</div>

