<tr>
    <td COLSPAN="2">
        <h4><?=$product->getName()?></h4>
        <?php if($product->getDescriptionShort()!==null):?>
            <div>
                <details>
                    <summary>Details</summary>
                    <p><?=$product->getDescriptionShort();?></p>
                </details>
            </div>
        <?php endif;?>
    </td>
    <td><?=$this->currencyFormat($product->getPrice(), "GBP", "en_GB"); ?>
        <i>/ <?=$product->getUnit()?></i>
    </td>
</tr>