<tr>
    <td COLSPAN="2">
        <h4><?=$product->getName()?></h4>
        <?php if($product->getDescriptionShort()!==null):?>
            <div>
                <details>
                    <summary>Details</summary>
                    <p><?=$product->getDescriptionShort();?></p>
                </details>
            </div>
        <?php endif;?>
    </td>
    <td><?php
        if($this->cartHelper()->allowCartCurrency() === true){
            $currentProductPriceUnit = ($product->getPrice()*$this->cartHelper()->getCurrencyRate());
        } else {
            $currentProductPriceUnit = ($product->getPrice());
        }
        echo $this->currencyFormat($currentProductPriceUnit, "GBP", "en_GB");
        ?>
        <i>/ <?=$product->getUnit()?></i>
    </td>
</tr>