<hr />
<div class="row">
    <div class="col-md-8">
        <h1 class="m-0">Stock In</h1>
    </div>
</div>
<script>
    window.onload = function() {
        document.getElementById("stock-barcode-search").focus();
    };
</script>

<hr />

<?php if(isset($messages)&&array_key_exists('error',$messages)):?>
    <?=$this->flashMessage($messages['error'],'error',true,true);?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('success',$messages)):?>
    <?=$this->flashMessage($messages['success'],'success',true,true);?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('info',$messages)):?>
    <?=$this->flashMessage($messages['info'],'info',true,true);?>
<?php endif;?>

<div class="row justify-content-around h-100 mb-4">
    <div class="col-sm-2">
        <button class="btn btn-lg btn-danger h-100 w-100">-</button>
    </div>
    <div class="col-sm-6">
        <?=$this->getFormAttached($forms,null,'stock_barcode_form',true,'stock-form::scan-in-form');?>
    </div>
    <div class="col-sm-2 ">
        <button class="btn btn-lg btn-success h-100 w-100">+</button>
    </div>
</div>

<hr />