<hr />
<div class="row">
    <div class="col-md-8">
        <h1>Stock List</h1>
    </div>
    <div class="col-md-4 text-right">
        <?=$this->getFormAttached($forms,null,'stock_barcode_form');?>
    </div>
</div>
<script>
    window.onload = function() {
        document.getElementById("stock-barcode-search").focus();
    };
</script>
<hr />

<?php if(isset($messages)&&array_key_exists('error',$messages)):?>
    <?=$this->flashMessage($messages['error'],'error');?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('info',$messages)):?>
    <?=$this->flashMessage($messages['info'],'info');?>
<?php endif;?>

<?php if( ! empty($list)): ?>
    <table class="table table-hover" style="table-layout: fixed;">
        <thead class="thead-light">
        <tr>
            <th COLSPAN="2">Name</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        <?php
        /* @var \Product\Model\ProductModel $product */
        foreach($paginator as $stockItem):
            echo $this->partial('stock::stock-list-table-row', ['stockItem'=>$stockItem,'forms'=>(isset($forms))?$forms:null]);
        endforeach; ?>
        </tbody>
    </table>

<?php endif; ?>

<hr />

<?php
echo $this->paginationControl($paginator,
    'Sliding',
    'common::pagination-control', array('route' => 'stock.product.list'));
?>

<hr />