<div class="row mt-4">
    <div class="col-md-12">
        <h1 class="m-0 text-muted">Stock Details</h1>
        <hr />
        <h2 class="m-0"><?=$product_data->getName();?></h2>
    </div>
</div>

<hr />

<a class="btn btn-sm btn-info" href="<?=$this->url('stock.product.write.update',['product_uid'=>$product_data->getProductUid()]);?>">Update</a>
<a class="btn btn-sm btn-danger" href="<?=$this->url('stock.product.write.remove',['product_uid'=>$product_data->getProductUid()]);?>">Delete</a>
<a class="btn btn-sm btn-secondary" href="<?=$this->url('stock.product.list');?>">Stock List</a>
<a class="btn btn-sm btn-secondary" href="<?=$this->url('stock.product.write.create');?>">Create Product</a>

<table class="table mt-3">
    <tbody>
    <tr>
        <th scope="row">Product Name</th>
        <td>
            <span><?=$product_data->getName();?></span>
        </td>
    </tr>
    <tr>
        <th scope="row">Product UID</th>
        <td><small><?=$product_data->getProductUid();?></small></td>
    </tr>
    <tr>
        <th scope="row">Summary</th>
        <td>
            <span><?=($product_data->getDescriptionShort())?$product_data->getDescriptionShort():'-';?></span>
        </td>
    </tr>
    <tr>
        <th scope="row">Stock Qty</th>
        <td>
            <span><?=$stock_data->getProductQty();?></span>
        </td>
    </tr>
    <tr>
        <th scope="row">Unit</th>
        <td>
            <span><?=$stock_data->getUnit();?></span>
        </td>
    </tr>
    <tr>
        <th scope="row">Price</th>
        <td>
            <span><?=$stock_data->getPrice();?></span>
        </td>
    </tr>
    <tr>
        <th scope="row">Status</th>
        <td>
            <?=( ! empty($status_data))?$this->displayStockStatus($status_data->getStatusCode(),true):'<i>unspecified ('.$stock_data->getStockStatus().')</i>';?>
        </td>
    </tr>
    <tr>
        <th scope="row">Barcodes</th>
        <td><?php
            if( ! empty($barcode_data->getItems())) {
                $barcodes = [];
                foreach($barcode_data->getItems() as $barcodeItem) {
                    $barcodes[] = $barcodeItem->getBarcodeValue();
                }
                echo implode(', ',$barcodes);
            } else {
                echo '<i>unspecified</i>';
            }
            ?>
        </td>
    </tr>
    </tbody>
</table>

<hr />

