<tr>
    <td COLSPAN="2">
        <a href="<?=$this->url('stock.product.details',['product_uid'=>$stockItem->getProductUid()]);?>"><?=$this->escapeHtml($stockItem->getName());?></a>
    </td>
    <td>
        <?php

        if(is_numeric($stockItem->getStatusCode())) {
            echo $this->displayStockStatus($stockItem->getStatusCode(),true);
        } elseif(is_null($stockItem->getStatusCode())) {
            echo $this->displayStockStatus($stockItem->getStockStatus(),true);
        } else {
            echo '<i>unspecified ('.$stockItem->getStockStatus().')</i>';
        }
        ?>
    </td>
    <td><?=$this->escapeHtml($stockItem->getProductQty());?></td>
    <td><?=$this->currencyFormat($stockItem->getPrice(), "GBP", "en_GB"); ?>
        <i>/ <?=$stockItem->getUnit()?></i>
    </td>
</tr>