<div class="row mt-4">
    <div class="col-md-12">
        <h1 class="m-0 text-muted">Stock Remove</h1>
            <hr />
            <h2 class="m-0">
                <strong class="text-dark">REMOVE:</strong>
                <span><?=$this->escapeHtml($product_data->getName());?></span>
            </h2>
    </div>
</div>

<hr />

<?php if(isset($messages)&&array_key_exists('error',$messages)):?>
    <?=$this->flashMessage($messages['error'],'error',true,true);?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('success',$messages)):?>
    <?=$this->flashMessage($messages['success'],'success',true,true);?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('info',$messages)):?>
    <?=$this->flashMessage($messages['info'],'info',true,true);?>
<?php endif;?>

<?php
$form->prepare();
echo $this->form()->openTag($form);
?>

<a class="btn btn-sm btn-info" href="<?=$this->url('stock.product.list');?>">Return</a>

<hr />

<p>Are you sure you want to remove <strong><?=$this->escapeHtml($product_data->getName());?></strong>?</p>

<?=$this->formElement($form->get('stock_product_remove_confirm'));?>
<div class="hidden">
    <?=$this->formElement($form->get('application_id'));?>
    <?=$this->formElement($form->get('product_uid'));?>
    <?=$this->formElement($form->get('stock_uid'));?>
    <?=$this->formElement($form->get('csrf'));?>
</div>
<?=$this->formElementErrors($form->get('application_id'));?>
<?=$this->formElementErrors($form->get('csrf'));?>

<?=$this->formSubmit($form->get('submit'));?>
<?php
echo $this->form()->closeTag();
?>
<hr />