<tr>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getVenueUid());?></td>
    <td COLSPAN="1">
        <a href="<?=$this->url('restable.admin.venue.list');?>"><?=$this->escapeHtml($item->getClientUid());?></a>
    </td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getStatus());?></td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getUpdated());?></td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getCreated());?></td>
</tr>