<hr />
<div class="row">
    <div class="col-md-8">
        <h1>Orders</h1>
    </div>
    <div class="col-md-4 text-right"></div>
</div>
<script>
    window.onload = function() {
        document.getElementById("stock-barcode-search").focus();
    };
</script>
<hr />
<?php if(isset($messages)&&array_key_exists('error',$messages)):?>
    <?=$this->flashMessage($messages['error'],'error');?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('info',$messages)):?>
    <?=$this->flashMessage($messages['info'],'info');?>
<?php endif;?>

<table class="table table-hover" style="table-layout: fixed;">
    <thead class="thead-light">
    <tr>
        <th>Name</th>
        <th>Venue</th>
        <th>Phone</th>
        <th>Email</th>
        <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <?php
    /* @var \Product\Model\ProductModel $product */
    foreach($paginator as $item):
        var_dump($item);
//        echo $this->partial('restable-admin::enquiries-list-table-row', ['item'=>$item,'forms'=>(isset($forms))?$forms:null]);
    endforeach; ?>
    </tbody>
</table>
<?php
echo $this->paginationControl($paginator,
    'Sliding',
    'common::pagination-control', array('route' => 'restable.admin.orders.list'));
?>
