<h1>Restable Dashboard</h1>

<?=$this->partial("restable-admin-partial::partial-header",['heading'=>$data_template_model['heading']]);?>

<?php if(isset($messages)&&array_key_exists('error',$messages)):?>
    <?=$this->flashMessage($messages['error'],'error');?>
<?php endif;?>
<?php if(isset($messages)&&array_key_exists('info',$messages)):?>
    <?=$this->flashMessage($messages['info'],'info');?>
<?php endif;?>
<h4>Demo Requests</h4>
<div class="table-responsive">
    <table class="table table-hover table-sm" style="table-layout: fixed;">
        <thead class="thead-light">
        <tr>
            <?php foreach($data_template_model['table'] as $table):?>
                <?php foreach($table['headers'] as $tableHeaderText):?>
                    <th><?=$this->escapeHtml($tableHeaderText);?></th>
                <?php endforeach;?>
            <?php endforeach;?>
        </tr>
        </thead>
        <tbody>
        <?php if($paginator->count()===0): ?>
            <tr>
                <td COLSPAN="10"><i>No data items.</i></td>
            </tr>
        <?php else:?>
            <?php foreach($paginator as $item): ?>
                <tr>
                    <?php if(array_key_exists('table_row',$view_template_model)):?>
                        <?=$this->partial(
                            $view_template_model['table_row'],
                            [
                                'item'=>$item,
                                'forms'=>(isset($forms))?$forms:null,
                                'data_template_model'=>(isset($data_template_model))?$data_template_model:null,
                            ]
                        );
                        ?>
                    <?php else: ?>
                        <?php foreach($data_template_model['table']['main']['rows'] as $tableRow):?>
                            <?php if(array_key_exists('column',$tableRow)):?>
                                <td><?=$this->escapeHtml($item->{$tableRow['column']});?></td>
                            <?php elseif(array_key_exists('buttons',$tableRow)):?>
                                <td><?=$this->displayLinkGroup($tableRow['buttons'],$item);?></td>
                            <?php endif;?>
                        <?php endforeach;?>
                    <?php endif;?>
                </tr>
            <?php endforeach; ?>
        <?php endif;?>
        </tbody>
    </table>
</div>
<h4>Applications Activity</h4>

<h4>Managers Activity</h4>

<h4>Stock Activity</h4>



