<tr>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getNameFirst() . ' ' . $item->getNameLast());?></td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getVenueName());?></td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getContactPhone());?></td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getContactEmail());?></td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getCreated());?></td>
</tr>