<tr>
    <td COLSPAN="1">
        <a href="<?=$this->url('restable.admin.application.list');?>"><?=$this->escapeHtml($item->getClientName());?></a>
    </td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getClientUid());?></td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getStatus());?></td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getUpdated());?></td>
    <td COLSPAN="1"><?=$this->escapeHtml($item->getCreated());?></td>
    <td COLSPAN="1"><a href="<?=$this->url('restable.admin.category.read');?>">Details</a></td>
</tr>